defaults: &defaults
  cool:
    saweet: nested settings
  neat_setting: 24
  aws_access_key_id: 0
  aws_secret_access_key: 0
  aws_s3_bucket: 0
  awesome_setting: <%= "Did you know 5 + 5 = #{5 + 5}?" %>

  
    




development:
  <<: *defaults
  neat_setting: 800

test:
  <<: *defaults

production:
  <<: *defaults